LOG_LEVEL="DEBUG"
DATA_URI="./data/State_of_Maryland_Payments_Data__FY2008_to_FY2024.csv.gz"
OUTPUT_URI="./temp/results.json"


# Ensure Java version is supported by spark. 
# See https://community.cloudera.com/t5/Community-Articles/Spark-and-Java-versions-Supportability-Matrix/ta-p/383669.
# JAVA_HOME=